"""empty message

Revision ID: 1adaf4332df3
Revises: 20d6e6a2438c
Create Date: 2025-10-16 00:28:23.333152+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1adaf4332df3'
down_revision: Union[str, Sequence[str], None] = '20d6e6a2438c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_order_movie_constraint'), 'order_items', type_='unique')
    op.create_unique_constraint('uq_order_movie', 'order_items', ['order_id', 'movie_id'])
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_unique_constraint('uq_user_order_id', 'orders', ['user_id', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_order_id', 'orders', type_='unique')
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_constraint('uq_order_movie', 'order_items', type_='unique')
    op.create_unique_constraint(op.f('unique_order_movie_constraint'), 'order_items', ['order_id', 'movie_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
