"""empty message

Revision ID: 20d6e6a2438c
Revises: 3156a5d971df
Create Date: 2025-10-15 19:36:57.229595+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d6e6a2438c'
down_revision: Union[str, Sequence[str], None] = '3156a5d971df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_likes', sa.Column('value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_likes', 'value')
    # ### end Alembic commands ###
